#!/bin/bash

if [ ! -e julia-1.7.0-rc2 ]; then
   wget https://julialang-s3.julialang.org/bin/linux/x64/1.7/julia-1.7.0-rc2-linux-x86_64.tar.gz
   tar -xvzf julia-1.7.0-rc2-linux-x86_64.tar.gz
   rm julia-1.7.0-rc2-linux-x86_64.tar.gz
fi

export JULIA_HOME=$(pwd)/julia-1.7.0-rc2
export PATH=$PATH:$JULIA_HOME/bin